version: '3'
services:
    sonar:
        build: ./sonar
    ui:
        build: ./ui
        # We can't mount the entire UI directory, since the `node_modules`
        # by default live at that location. Instead we mount the specific
        # collection of files that should propagate from the host to the
        # container.
        volumes:
            - ./ui/src:/usr/local/src/skiff/app/ui/src
            - ./ui/public:/usr/local/src/skiff/app/ui/public
            - ./ui/package.json:/usr/local/src/skiff/app/ui/package.json
            - ./ui/tsconfig.json:/usr/local/src/skiff/app/ui/tsconfig.json
            - ./ui/yarn.lock:/usr/local/src/skiff/app/ui/yarn.lock
        tty: true
    proxy:
        build: ./proxy
        ports:
            - 8080:80
